version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/api  
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app_network  
  php:
    build: docker/php
    #image: php:7-fpm
    volumes:
      - ./:/var/www/api
    depends_on:
      - mysql
    #environment:
    #   XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1
    networks:
      - app_network    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    restart: always
    networks:
      - app_network
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysql:/var/lib/mysql        
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysymfony
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - 3306:3306
    restart: always
    networks:
      - app_network
  jenkins:
    image: jenkins/jenkins:latest
    ports:
      - 8090:8080
    networks:
      - app_network
networks:
  app_network:
      driver: bridge